-- MySQL Script generated by MySQL Workbench
-- Sat Dec  5 17:09:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetopi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetopi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetopi` DEFAULT CHARACTER SET utf8 ;
USE `projetopi` ;

-- -----------------------------------------------------
-- Table `projetopi`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetopi`.`Cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(14) NOT NULL,
  `RG` VARCHAR(12) NULL,
  `Nome` VARCHAR(255) NULL,
  `Data_nascimento` DATE NULL,
  `Tel` VARCHAR(255) NULL,
  `e-maill` VARCHAR(255) NULL,
  `Rua` VARCHAR(45) NULL,
  `complemento` VARCHAR(255) NULL,
  `Numero` INT NULL,
  `Cep` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`id_cliente`, `CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetopi`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetopi`.`Livro` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `Cod_livro` VARCHAR(255) NOT NULL,
  `Titulo_Livro` VARCHAR(255) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Qtd_Livro` INT NULL,
  `cod_barras` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `editora` VARCHAR(45) NULL,
  PRIMARY KEY (`id_livro`, `Cod_livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetopi`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetopi`.`pedido` (
  `num_pedido` INT NOT NULL AUTO_INCREMENT,
  `valor_pedido` DECIMAL(10,2) NULL,
  `Data_Compra` DATE NULL,
  `qtde` VARCHAR(45) NULL,
  `desc_produto` VARCHAR(45) NULL,
  `Livro_id_livro` INT NOT NULL,
  `Cliente_id_cliente` INT NOT NULL,
  `Cliente_CPF` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`num_pedido`),
  INDEX `fk_pedido_Cliente1_idx` (`Cliente_id_cliente` ASC, `Cliente_CPF` ASC) VISIBLE,
  INDEX `fk_pedido_Livro1_idx` (`Livro_id_livro` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_Cliente1`
    FOREIGN KEY (`Cliente_id_cliente` , `Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`id_cliente` , `CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Livro1`
    FOREIGN KEY (`Livro_id_livro`)
    REFERENCES `mydb`.`Livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
